# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
dist: trusty
cache: packages
r:
  - bioc-release
use_bioc: true
bioc_packages:
r_github_packages:
script:
   - R CMD build . --resave-data
   - R CMD check *tar.gz --as-cran
